In [2]:
import pandas as pd

df = pd.read_csv(r"C:\dev\web-personal\html-web\scripts\raw\vehicles.csv", low_memory=False)

print(df.shape)

(50407, 84)

In [3]:
import os

In [4]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

In [5]:
print(df.columns.tolist())

['barrels08', 'barrelsA08', 'charge120', 'charge240', 'city08', 'city08U', 'cityA08', 'cityA08U', 'cityCD', 'cityE', 'cityUF', 'co2', 'co2A', 'co2TailpipeAGpm', 'co2TailpipeGpm', 'comb08', 'comb08U', 'combA08', 'combA08U', 'combE', 'combinedCD', 'combinedUF', 'cylinders', 'displ', 'drive', 'engId', 'eng_dscr', 'feScore', 'fuelCost08', 'fuelCostA08', 'fuelType', 'fuelType1', 'ghgScore', 'ghgScoreA', 'highway08', 'highway08U', 'highwayA08', 'highwayA08U', 'highwayCD', 'highwayE', 'highwayUF', 'hlv', 'hpv', 'id', 'lv2', 'lv4', 'make', 'model', 'mpgData', 'phevBlended', 'pv2', 'pv4', 'range', 'rangeCity', 'rangeCityA', 'rangeHwy', 'rangeHwyA', 'trany', 'UCity', 'UCityA', 'UHighway', 'UHighwayA', 'VClass', 'year', 'youSaveSpend', 'baseModel', 'guzzler', 'trans_dscr', 'tCharger', 'sCharger', 'atvType', 'fuelType2', 'rangeA', 'evMotor', 'mfrCode', 'c240Dscr', 'charge240b', 'c240bDscr', 'createdOn', 'modifiedOn', 'startStop', 'phevCity', 'phevHwy', 'phevComb']

In [6]:
print(df["atvType"].value_counts(dropna=False))

atvType
NaN               43547
Hybrid             1899
EV                 1608
FFV                1538
Diesel             1246
Plug-in Hybrid      447
CNG                  50
FCV                  42
Bifuel (CNG)         20
Bifuel (LPG)          8
eFCV                  2
Name: count, dtype: int64

In [7]:
phev = df[df["atvType"] == "Plug-in Hybrid"]
phev.shape

(447, 84)

In [8]:
phev.notna().sum().sort_values(ascending=False)

barrels08          447
barrelsA08         447
charge120          447
charge240          447
city08             447
city08U            447
cityA08            447
cityA08U           447
cityCD             447
cityE              447
cityUF             447
co2                447
co2A               447
co2TailpipeAGpm    447
co2TailpipeGpm     447
comb08             447
comb08U            447
combA08            447
combA08U           447
combE              447
combinedCD         447
combinedUF         447
cylinders          447
displ              447
drive              447
engId              447
feScore            447
fuelCost08         447
ghgScore           447
fuelCostA08        447
fuelType           447
fuelType1          447
highway08          447
ghgScoreA          447
highway08U         447
highwayA08         447
lv2                447
highwayA08U        447
highwayCD          447
highwayE           447
highwayUF          447
hlv                447
hpv                447
id                 447
mpgData            447
lv4                447
make               447
model              447
pv2                447
phevBlended        447
pv4                447
range              447
phevHwy            447
rangeCity          447
rangeCityA         447
rangeHwy           447
rangeHwyA          447
trany              447
UCity              447
UCityA             447
UHighway           447
UHighwayA          447
VClass             447
year               447
youSaveSpend       447
baseModel          447
atvType            447
fuelType2          447
phevComb           447
phevCity           447
evMotor            447
rangeA             447
startStop          447
modifiedOn         447
createdOn          447
charge240b         447
mfrCode            446
eng_dscr           422
tCharger           307
sCharger            34
guzzler             12
trans_dscr           0
c240Dscr             0
c240bDscr            0
dtype: int64

## Explicacion del codigo
phev.notna() crea una tabla de True/False: True donde hay dato y False donde está vacío.
.sum() suma por columnas. Como True cuenta como 1, el resultado es cuántos coches tienen dato en cada columna.
.sort_values(ascending=False) ordena de más a menphev.notna() crea una tabla de True/False: True donde hay dato y False donde está vacío.

In [9]:
phev["sCharger"].describe()

count     34
unique     1
top        S
freq      34
Name: sCharger, dtype: object

In [10]:
columnas = ["id", "make", "model", "baseModel", "year", "VClass",
            "comb08", "combE", "rangeA", "charge240", "co2TailpipeGpm",
            "displ", "cylinders", "drive", "trany", "evMotor"]

phev = phev[columnas]
phev.dtypes

id                  int64
make                  str
model                 str
baseModel             str
year                int64
VClass                str
comb08              int64
combE             float64
rangeA                str
charge240         float64
co2TailpipeGpm    float64
displ             float64
cylinders         float64
drive                 str
trany                 str
evMotor               str
dtype: object

In [11]:
phev.describe()

,id,year,comb08,combE,charge240,co2TailpipeGpm,displ,cylinders
count,447.000000,447.000000,447.000000,447.000000,447.000000,447.000000,447.000000,447.000000
mean,43782.534676,2021.140940,28.158837,51.546085,3.141096,180.033557,2.441611,4.937360
std,4487.750414,3.427703,9.056094,14.445111,1.187138,93.413235,0.878704,1.579185
min,30980.000000,2011.000000,13.000000,25.000000,0.670000,22.000000,0.600000,2.000000
25%,40810.500000,2019.000000,21.000000,41.000000,2.500000,106.000000,2.000000,4.000000
50%,43913.000000,2021.000000,26.000000,51.000000,3.000000,165.000000,2.000000,4.000000
75%,47498.500000,2024.000000,33.000000,64.000000,3.400000,236.000000,3.000000,6.000000
max,50707.000000,2027.000000,54.000000,86.000000,9.000000,486.000000,4.600000,8.000000

In [12]:
phev[phev["displ"] == phev["displ"].min()]

,id,make,model,baseModel,year,VClass,comb08,combE,rangeA,charge240,co2TailpipeGpm,displ,cylinders,drive,trany,evMotor
27755,35279,BMW,i3 REX,i3,2014,Subcompact Cars,39,29.0,72,4.0,40.0,0.6,2.0,Rear-Wheel Drive,Automatic (A1),125kW
28585,36030,BMW,i3 REX,i3,2015,Subcompact Cars,39,29.0,72,4.0,40.0,0.6,2.0,Rear-Wheel Drive,Automatic (A1),125kW
29888,37222,BMW,i3 REX,i3,2016,Subcompact Cars,39,29.0,72,4.0,37.0,0.6,2.0,Rear-Wheel Drive,Automatic (A1),125kW
31002,38229,BMW,i3 REX (94 Amp-hour battery),i3,2017,Subcompact Cars,35,30.0,97,5.0,29.0,0.6,2.0,Rear-Wheel Drive,Automatic (A1),125kW AC Induction
32783,39834,BMW,i3 (94Ah) with Range Extender,i3,2018,Subcompact Cars,35,31.0,97,5.0,29.0,0.6,2.0,Rear-Wheel Drive,Automatic (A1),125 kW AC Induction
32784,39835,BMW,i3s (94Ah) with Range Extender,i3,2018,Subcompact Cars,35,31.0,97,5.0,29.0,0.6,2.0,Rear-Wheel Drive,Automatic (A1),125 kW AC Induction
34308,41211,BMW,i3 with Range Extender,i3,2019,Subcompact Cars,31,32.0,126,7.0,22.0,0.6,2.0,Rear-Wheel Drive,Automatic (A1),125 kW AC Induction
34309,41212,BMW,i3s with Range Extender,i3,2019,Subcompact Cars,31,32.0,126,7.0,22.0,0.6,2.0,Rear-Wheel Drive,Automatic (A1),135 kW AC Induction
35800,42572,BMW,i3 with Range Extender,i3,2020,Subcompact Cars,31,32.0,126,7.0,22.0,0.6,2.0,Rear-Wheel Drive,Automatic (A1),125 kW DCPM
35801,42573,BMW,i3s with Range Extender,i3,2020,Subcompact Cars,31,32.0,126,7.0,22.0,0.6,2.0,Rear-Wheel Drive,Automatic (A1),135 kW DCPM
37088,43745,BMW,i3 with Range Extender,i3,2021,Subcompact Cars,31,32.0,126,7.0,22.0,0.6,2.0,Rear-Wheel Drive,Automatic (A1),125 kW DCPM
37089,43746,BMW,i3s with Range Extender,i3,2021,Subcompact Cars,31,32.0,126,7.0,22.0,0.6,2.0,Rear-Wheel Drive,Automatic (A1),135 kW DCPM

In [13]:
phev["rangeA"].value_counts()

rangeA
14     35
19     30
22     21
33     19
21     19
17     18
18     18
26     18
20     17
37     15
32     14
16     13
40     12
29     12
30     12
15     11
31     11
38      9
27      9
25      9
8       9
11      8
34      8
12      7
36      7
28      7
9       6
126     6
35      5
48      5
42      5
24      5
7       5
53      4
10      4
23      4
72      3
97      3
45      3
1       3
13      2
61      2
52      2
54      2
51      2
44      2
56      1
50      1
39      1
43      1
41      1
6       1
Name: count, dtype: int64

In [14]:
numeros = pd.to_numeric(phev["rangeA"], errors="coerce")
phev.loc[numeros.isna(), ["make", "model", "year", "rangeA"]]

Empty DataFrame
Columns: [make, model, year, rangeA]
Index: []

In [15]:
phev["rangeA"] = pd.to_numeric(phev["rangeA"])
phev["cylinders"] = phev["cylinders"].astype(int)
phev.dtypes

id                  int64
make                  str
model                 str
baseModel             str
year                int64
VClass                str
comb08              int64
combE             float64
rangeA              int64
charge240         float64
co2TailpipeGpm    float64
displ             float64
cylinders           int64
drive                 str
trany                 str
evMotor               str
dtype: object

In [16]:
phev.columns.tolist()

['id',
 'make',
 'model',
 'baseModel',
 'year',
 'VClass',
 'comb08',
 'combE',
 'rangeA',
 'charge240',
 'co2TailpipeGpm',
 'displ',
 'cylinders',
 'drive',
 'trany',
 'evMotor']

In [17]:
phev["consumo_l100km"] = (235.215 / phev["comb08"]).round(1)
phev["consumo_kwh100km"] = (phev["combE"] / 1.609344).round(1)
phev["co2_gkm"] = (phev["co2TailpipeGpm"] / 1.609344).round(0).astype(int)
phev["autonomia_km"] = (phev["rangeA"] * 1.609344).round(0).astype(int)

In [18]:
phev[["comb08", "consumo_l100km", "rangeA", "autonomia_km"]].head()

       comb08  consumo_l100km  rangeA  autonomia_km
23033      37             6.4      35            56
23735      37             6.4      35            56
24686      50             4.7      11            18
24722      20            11.8      33            53
24875      37             6.4      38            61

In [19]:
nombres = {
    "id": "id",
    "make": "marca",
    "model": "modelo",
    "year": "anio",
    "VClass": "carroceria",
    "consumo_l100km": "consumo_l100km",
    "consumo_kwh100km": "consumo_kwh100km",
    "autonomia_km": "autonomia_km",
    "charge240": "carga_horas",
    "co2_gkm": "co2_gkm",
    "displ": "cilindrada_l",
    "cylinders": "cilindros",
    "drive": "traccion",
    "trany": "transmision",
}

coches = phev[list(nombres.keys())].rename(columns=nombres)
coches.head()

,id,marca,modelo,anio,carroceria,consumo_l100km,consumo_kwh100km,autonomia_km,carga_horas,co2_gkm,cilindrada_l,cilindros,traccion,transmision
23033,30980,Chevrolet,Volt,2011,Compact Cars,6.4,22.4,56,4.0,52,1.4,4,Front-Wheel Drive,Automatic (variable gear ratios)
23735,31618,Chevrolet,Volt,2012,Compact Cars,6.4,22.4,56,4.0,54,1.4,4,Front-Wheel Drive,Automatic (variable gear ratios)
24686,32484,Toyota,Prius Plug-in Hybrid,2012,Midsize Cars,4.7,18.0,18,1.5,83,1.8,4,Front-Wheel Drive,Automatic (variable gear ratios)
24722,32516,Fisker,Karma,2012,Subcompact Cars,11.8,38.6,53,6.0,105,2.0,4,Rear-Wheel Drive,Automatic (A1)
24875,32655,Chevrolet,Volt,2013,Compact Cars,6.4,21.7,61,4.0,50,1.4,4,Front-Wheel Drive,Automatic (variable gear ratios)

In [20]:
coches.to_json("../datos/coches.json", orient="records", force_ascii=False, indent=2)

## explicacion codigo
"../datos/coches.json": los dos puntos significan “sube una carpeta”. Como el notebook está en scripts/, sube a la raíz del proyecto y entra en datos/.
orient="records" genera una lista de objetos, uno por coche. Es el formato que mejor entiende JavaScript.
force_ascii=False guarda las tildes tal cual en lugar de convertirlas en códigos como \u00ed.
indent=2 lo deja con sangría, legible para un humano.

In [21]:
os.getcwd()

'c:\\dev\\web-personal\\html-web\\scripts'